var nombre = "samuel";
let edad = 17;
const ciudad = "medellin";
console.log("nombre:");
console.log(nombre);
console.log("edad:");
console.log(edad);
console.log("ciudad:");
console.log(ciudad);
console.log("la edad es:");
console.log(edad);
console.log ("ciudad: ",ciudad);
console.log ("nombre:" ,nombre,"edad: ",edad ,"ciudad: ",ciudad);